# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Thickheaded.Me
subtitle: Lets Rock
description: A Thickheaded X Blog
author: Thickheaded X
language: zh-Hans
timezone: Asia/Harbin

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://thickheaded.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: https://github.com/upupxjg/upupxjg.github.io.git
    branch: master
  - type: git
    repo: git@note.thickheaded.me:/home/git/hexo.git
    branch: master
  - type: git
    repo: git@www.thickheaded.me:/home/git/hexo.git
    branch: master
    #  - type: git
    #repo: git@git.coding.net:upupxjg/upupxjg.coding.me.git
    #branch: hexo
    #extend_dirs: /
    #ignore_hidden: false
    #ignore_pattern:
    #    public: .

algolia:
  applicationID: '58UE9N8MKH'
  apiKey: 'b399fed96dd597b7f1461dab9771cf4b'
  adminApiKey: 'f6522e5c5ea1d0ff3663b01f432f9d3a'
  indexName: 'thickheaded.me.index'
  chunkSize: 5000

qiniu:
  offline: false
  sync: true
  bucket: hexocdn
  secret_file: sec/qn.json 
  dirprefix: static
  urlPrefix: https://static.thickheaded.me/static
  up_host: http://up-z1.qiniu.com
  local_dir: static
  update_exist: false
  image:
      folder: images
      extend: -common
